/**
 * Load precomputed analytics JSON (generated by npm run precompute).
 */

export interface PrecomputedData {
  kpis: { totalRevenue: number; totalTransactions: number; averageOrderValue: number; activeCustomers: number };
  trendDataDaily: { date: string; revenue: number; transactions: number; customers: number }[];
  trendDataWeekly: { date: string; revenue: number; transactions: number; customers: number }[];
  trendDataMonthly: { date: string; revenue: number; transactions: number; customers: number }[];
  dayOfWeekData: { day: string; revenue: number; transactions: number; customers: number }[];
  colorTrends: { date: string; [k: string]: string | number }[];
  sizeTrends: { date: string; [k: string]: string | number }[];
  customerSegments: { segment: string; count: number; totalRevenue: number; averageRevenue: number; percentage: number }[];
  productTrendsWeekly: { date: string; [k: string]: string | number }[];
  productTrendsMonthly: { date: string; [k: string]: string | number }[];
  collectionTrendsWeekly: { date: string; [k: string]: string | number }[];
  collectionTrendsMonthly: { date: string; [k: string]: string | number }[];
  categoryTrendsWeekly: { date: string; [k: string]: string | number }[];
  categoryTrendsMonthly: { date: string; [k: string]: string | number }[];
  productPerformanceWithStores: { name: string; totalRevenue: number; stores: { storeName: string; revenue: number }[] }[];
  collectionPerformanceWithStores: { name: string; totalRevenue: number; stores: { storeName: string; revenue: number }[] }[];
  categoryPerformanceWithStores: { name: string; totalRevenue: number; stores: { storeName: string; revenue: number }[] }[];
  colorPerformanceWithStores: { name: string; totalRevenue: number; stores: { storeName: string; revenue: number }[] }[];
  sizePerformanceWithStores: { name: string; totalRevenue: number; stores: { storeName: string; revenue: number }[] }[];
  storePerformanceWithProducts: { name: string; totalRevenue: number; stores: { storeName: string; revenue: number }[] }[];
  storeTrendsWeekly: { date: string; [k: string]: string | number }[];
  storeTrendsMonthly: { date: string; [k: string]: string | number }[];
  rfmMatrix: unknown[];
  frequencySegments: unknown[];
  ageSegments: unknown[];
  genderSegments: unknown[];
  channelSegments: unknown[];
  aovSegments: unknown[];
  employeePerformance: unknown[];
  brandPerformance: { brandCode: string; brandName: string; totalRevenue: number; transactions: number; customers: number; averageOrderValue: number; storeCount: number }[];
}

let cachedData: PrecomputedData | null = null;

export async function loadPrecomputedData(): Promise<PrecomputedData> {
  if (cachedData) {
    return cachedData;
  }

  const baseUrl = import.meta.env.BASE_URL ?? "/";
  const url = `${baseUrl}data/precomputed.json`;

  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(
      `Failed to load precomputed data from ${url}: ${response.statusText}. Run "npm run precompute" before build.`
    );
  }

  const data = (await response.json()) as PrecomputedData;
  if (!data.kpis || !data.trendDataMonthly || !data.productTrendsMonthly) {
    throw new Error('Invalid precomputed data format. Regenerate with "npm run precompute".');
  }

  cachedData = data;
  return data;
}
